@Library('mylibrary')_

pipeline
{
    agent any
    stages
    {
        stage('Download_Master')
        {
            steps
            {
                script
                {
                    cicd.gitDownload("maven")
                }
            }
        }
        stage('Build_Master')
        {
            steps
            {
                script
                {
                    cicd.buildArtifacts()
                }
            }
        }
        stage('Deploy_Master')
        {
            steps
            {
                script
                {
                    cicd.deployTomcat("DeclarativePipelIneWithSharedLibrary","54.226.208.26","testapp")
                }
            }
        }
         stage('Testing_Master')
        {
            steps
            {
                script
                {
                      cicd.gitDownload("FunctionalTesting")
                      cicd.executeSelenium("DeclarativePipelIneWithSharedLibrary")
                }
            }
        }
        
    }
}  
